export const CONFIG = {
  baseUrl: process.env.TREASURE_BASE_URL || "https://propfirmpayless.com",
  outputDir: process.env.TREASURE_OUTPUT_DIR || ".treasure-hunt",
  maxPagesFromSitemap: Number(process.env.TREASURE_MAX_PAGES || 120),
  fetchTimeoutMs: Number(process.env.TREASURE_FETCH_TIMEOUT_MS || 20000),
  pageConcurrency: Number(process.env.TREASURE_PAGE_CONCURRENCY || 8),
  assetConcurrency: Number(process.env.TREASURE_ASSET_CONCURRENCY || 10),
  watchIntervalSec: Number(process.env.TREASURE_WATCH_INTERVAL_SEC || 12),
  dynamicWaitMs: Number(process.env.TREASURE_DYNAMIC_WAIT_MS || 12000),
  longAnimationWaitMs: Number(process.env.TREASURE_LONG_WAIT_MS || 22000),
  quickDynamicWaitMs: Number(process.env.TREASURE_QUICK_DYNAMIC_WAIT_MS || 2400),
  quickLongAnimationWaitMs: Number(process.env.TREASURE_QUICK_LONG_WAIT_MS || 6500),
  quickMaxPages: Number(process.env.TREASURE_QUICK_MAX_PAGES || 18),
  screenshotLimit: Number(process.env.TREASURE_SCREENSHOT_LIMIT || 20),
  routes: [
    "/",
    "/offers",
    "/giveaway",
    "/glossary",
    "/glossary/intraday-stop",
    "/companies",
    "/tools",
    "/blog"
  ],
  watchRoutes: [
    "/glossary/intraday-stop",
    "/glossary",
    "/giveaway",
    "/offers",
    "/"
  ],
  suspiciousKeywords: [
    "gift",
    "present",
    "treasure",
    "hunt",
    "chest",
    "box",
    "prize",
    "surprise",
    "bonus",
    "giveaway",
    "rapid",
    "mffu",
    "intraday",
    "אוצר",
    "מטמון",
    "מתנה",
    "פרס",
    "הגרלה",
    "בזק",
    "ראפיד"
  ],
  clickKeywords: [
    "demo",
    "animation",
    "play",
    "start",
    "continue",
    "next",
    "open",
    "watch",
    "demo",
    "הדגמה",
    "אנימציה",
    "נגן",
    "התחל",
    "המשך",
    "הבא",
    "פתח",
    "צפה"
  ],
  closeKeywords: [
    "close",
    "dismiss",
    "skip",
    "accept",
    "ok",
    "continue",
    "סגור",
    "דלג",
    "אישור",
    "הבנתי",
    "סבבה"
  ],
  likelyImageExtensions: [".png", ".jpg", ".jpeg", ".webp", ".gif", ".svg", ".avif"]
};
